services:
  caddy:
    image: caddy:2-alpine
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - evo-frontend
      - evo-crm
      - evo-auth
      - evo-core
      - evo-processor

volumes:
  caddy_data:
  caddy_config:
